# Generated by Django 2.2.5 on 2019-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.FileField(blank=True, upload_to='about_image')),
                ('about_title', models.CharField(max_length=200)),
                ('about_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('profilepicture', models.FileField(blank=True, upload_to='artist_image')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.FileField(blank=True, upload_to='featured_image')),
                ('featured_title', models.CharField(max_length=200)),
                ('featured_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=200)),
                ('car_image', models.FileField(blank=True, upload_to='carousel_image')),
                ('car_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='post_image')),
            ],
        ),
    ]
