# Generated by Django 2.2.5 on 2019-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='portrait',
            field=models.BooleanField(default=True),
        ),
    ]
