# Generated by Django 2.2.5 on 2019-11-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_portrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='portrait',
            new_name='landscape',
        ),
    ]
